### ISSUE TITLE
bug: use mysql keyword or reserved word in table pages with error="Error 1064: You have an error in your SQL syntax; 

### ISSUE THREAD

**Issue by dyrnq** [ArtalkJS/ArtalkGo#13]
```bash
ERRO[0181] SELECT * FROM `pages` WHERE (key = 'http://127.0.0.1:8888/post/java-urlencoder' AND site_name = '唔该博客') AND `pages`.`deleted_at` IS NULL ORDER BY `pages`.`id` LIMIT 1 [704.131µs]  error="Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = ? AND site_name = ?) AND `pages`.`deleted_at` IS NULL ORDER BY `pages`.`id' at line 1"

```
column  key in table pages and notifies is mysql reserved word
| table    | model code                                                           | query code                                                           |
|----------|----------------------------------------------------------------------|----------------------------------------------------------------------|
| pages    | https://github.com/ArtalkJS/ArtalkGo/blob/v2.0.5/model/page.go#L16   | https://github.com/ArtalkJS/ArtalkGo/blob/v2.0.5/model/query.go#L193 |
| notifies | https://github.com/ArtalkJS/ArtalkGo/blob/v2.0.5/model/notify.go#L22 | https://github.com/ArtalkJS/ArtalkGo/blob/v2.0.5/model/query.go#L103 |

**Comment by qwqcode** [comment]
最新版已修复，感谢反馈
https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.0.6
