### ISSUE TITLE
MariaDB数据库错误

### ISSUE THREAD

**Issue by imycard** [ArtalkJS/ArtalkGo#14]
使用 MariaDB 10.5.12数据库，连接方式使用mysql。
启动后数据库只创建了sites表，报如下错误
ERROR CREATE TABLE `pages` (`id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`key` varchar(191),`title` longtext,`admin_only` boolean,`site_name` varchar(191),`vote_up` bigint,`vote_down` bigint,PRIMARY KEY (`id`),INDEX idx_pages_deleted_at (`deleted_at`),INDEX idx_pages_key (`key`),INDEX idx_pages_site_name (`site_name`),CONSTRAINT `fk_pages_site` FOREIGN KEY (`site_name`) REFERENCES `sites`(`name`)) [505.1µs] error=Error 1005: Can't create table `artalk`.`pages` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR SELECT * FROM `users` WHERE (LOWER(name) = LOWER('admin') AND LOWER(email) = LOWER('admin@example.com')) AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1 [537.9µs] error=Error 1146: Table 'artalk.users' doesn't exist
ERROR INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`email`,`link`,`password`,`badge_name`,`badge_color`,`last_ip`,`last_ua`,`is_admin`,`is_in_conf`) VALUES ('2022-02-08 04:26:29.312','2022-02-08 04:26:29.312',NULL,'admin','admin@example.com','','','管理员','#FF6C00','','',true,true) [518.5µs] error=Error 1146: Table 'artalk.users' doesn't exist
ERROR SELECT * FROM `users` WHERE is_in_conf = 1 AND `users`.`deleted_at` IS NULL [0s] error=Error 1146: Table 'artalk.users' doesn't exist

**Comment by imycard** [comment]
数据库换成8.0.28后报如下错误
ERROR CREATE TABLE `sites` (`id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`name` longtext,`urls` longtext,`users` longtext,PRIMARY KEY (`id`),INDEX idx_sites_deleted_at (`deleted_at`),UNIQUE INDEX idx_sites_name (`name`)) [504.7µs] error=Error 1170: BLOB/TEXT column 'name' used in key specification without a key length
ERROR SELECT * FROM `sites` WHERE name = '默认站点' AND `sites`.`deleted_at` IS NULL ORDER BY `sites`.`id` LIMIT 1 [504.4µs] error=Error 1146: Table 'artalk.sites' doesn't exist
ERROR INSERT INTO `sites` (`created_at`,`updated_at`,`deleted_at`,`name`,`urls`,`users`) VALUES ('2022-02-08 07:08:26.714','2022-02-08 07:08:26.714',NULL,'默认站点','','') [504.5µs] error=Error 1146: Table 'artalk.sites' doesn't exist
ERROR Create Site error: Error 1146: Table 'artalk.sites' doesn't exist
ERROR SELECT * FROM `users` WHERE (LOWER(name) = LOWER('admin') AND LOWER(email) = LOWER('admin@example.com')) AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1 [517µs] error=Error 1146: Table 'artalk.users' doesn't exist
ERROR INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`email`,`link`,`password`,`badge_name`,`badge_color`,`last_ip`,`last_ua`,`is_admin`,`is_in_conf`) VALUES ('2022-02-08 07:08:26.715','2022-02-08 07:08:26.715',NULL,'admin','admin@example.com','','','管理员','#FF6C00','','',true,true) [0s] error=Error 1146: Table 'artalk.users' doesn't exist
ERROR SELECT * FROM `users` WHERE is_in_conf = 1 AND `users`.`deleted_at` IS NULL [0s] error=Error 1146: Table 'artalk.users' doesn't exist

**Comment by keven1024** [comment]
百度
![屏幕截图 2022-02-17 083728](https://user-images.githubusercontent.com/99848979/154381741-189f888d-411d-4706-a9db-dd5b45786c3d.png)
![屏幕截图 2022-02-17 083803](https://user-images.githubusercontent.com/99848979/154383761-0f0c2288-2313-4725-a6b9-ebe664266059.png)
![屏幕截图 2022-02-17 083828](https://user-images.githubusercontent.com/99848979/154383822-732fc4fd-9cf2-4ca6-bcf7-fe6e49741d2f.png)
如果看不懂的话，也可以[付费](https://mianbaoduo.com/o/bread/YZaWk5pu)获得改好的sql代码

**Comment by qwqcode** [comment]
由于创建数据表直接使用了 Golang 的 ORM 框架 Gorm，之前开发也没有测试到有这些问题

目前 ArtalkGo 使用 MariaDB 和 MySQL 数据库需要“曲线救国”的方式....

1. 才疏学浅，某些表里面使用了 MySQL 的保留关键字（例如：key, name）作为字段名，所以会有问题（而 SQLite 没问题）
2. Golang 的 ORM 框架 Gorm 自动创建数据功能，似乎生成的 SQL 语句不太兼容一些种类的数据库

之后有时间会修改，但修改数据表结构，版本更新老版本与新版，对老用户来说，数据迁移又是一个麻烦事 🥲🥲🥲

**Comment by keven1024** [comment]
> 由于创建数据表直接使用了 Golang 的 ORM 框架 Gorm，之前开发也没有测试到有这些问题
> 
> 目前 ArtalkGo 使用 MariaDB 和 MySQL 数据库需要“曲线救国”的方式....
> 
> 1. 才疏学浅，某些表里面使用了 MySQL 的保留关键字（例如：key, name）作为字段名，所以会有问题（而 SQLite 没问题）
> 2. Golang 的 ORM 框架 Gorm 自动创建数据功能，似乎生成的 SQL 语句不太兼容一些种类的数据库
> 
> 之后有时间会修改，但修改数据表结构，版本更新老版本与新版，对老用户来说，数据迁移又是一个麻烦事 🥲🥲🥲

很惭愧，原本弄个付费链接就是希望大部分人好好使用百度，在百度和谷歌找不到解决方案的时候再过来提issue，没想到第一个付费的竟然是大佬您QAQ

其实个人觉得大佬您已经做的很好了，毕竟是开源软件，又不是商业软件，用户本身就应该有解决一些简单问题的能力，而不是把issue当成0成本免费获得帮助的地方，别人的时间和精力也是很宝贵的QAQ

**Comment by imycard** [comment]
> > 由于创建数据表直接使用了 Golang 的 ORM 框架 Gorm，之前开发也没有测试到有这些问题
> > 目前 ArtalkGo 使用 MariaDB 和 MySQL 数据库需要“曲线救国”的方式....
> > 
> > 1. 才疏学浅，某些表里面使用了 MySQL 的保留关键字（例如：key, name）作为字段名，所以会有问题（而 SQLite 没问题）
> > 2. Golang 的 ORM 框架 Gorm 自动创建数据功能，似乎生成的 SQL 语句不太兼容一些种类的数据库
> > 
> > 之后有时间会修改，但修改数据表结构，版本更新老版本与新版，对老用户来说，数据迁移又是一个麻烦事 🥲🥲🥲
> 
> 很惭愧，原本弄个付费链接就是希望大部分人好好使用百度，在百度和谷歌找不到解决方案的时候再过来提issue，没想到第一个付费的竟然是大佬您QAQ
> 
> 其实个人觉得大佬您已经做的很好了，毕竟是开源软件，又不是商业软件，用户本身就应该有解决一些简单问题的能力，而不是把issue当成0成本免费获得帮助的地方，别人的时间和精力也是很宝贵的QAQ

你要是能贡献代码或者提供建议就贡献，只是一个正常反馈bug、解决bug的过程被你上纲上线，还在我的issues里指责我发issues，并发收费解决连接，利用作者尚未解决的bug企图盈利。本来就是开源项目，发现bug难道不需要向作者反馈吗？反馈了一定就必须是作者解决？你有能力你也可以提交代码修补或改进啊。你为啥不希望改进的十全十美，因为完善后你这样的人无利可图了。

做人不能太无耻！！！
<img width="278" alt="微信截图_20220218130121" src="https://user-images.githubusercontent.com/3360809/154621525-02770cab-f41c-4a81-97dd-1811d029fc6a.png">
<img width="522" alt="微信截图_20220218130212" src="https://user-images.githubusercontent.com/3360809/154621529-caca3c01-65d1-41d7-8e39-4c078393d87f.png">
