### ISSUE TITLE
关于连接 MariaDB 和 MySQL 数据库的问题

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/ArtalkGo#15]
由于创建数据表直接使用了 Golang 的 ORM 框架 Gorm，之前开发也没有测试到有这些问题

目前 ArtalkGo 使用 MariaDB 和 MySQL 数据库需要“曲线救国”的方式....

1. 才疏学浅，某些表里面使用了 MySQL 的保留关键字（例如：key, name）作为字段名，所以会有问题（而 SQLite 没问题）
2. Golang 的 ORM 框架 Gorm 自动创建数据功能，似乎生成的 SQL 语句不太兼容一些种类的数据库

之后有时间会修改，但修改数据表结构，版本更新老版本与新版，对老用户来说，数据迁移又是一个麻烦事 🥲🥲🥲

_Originally posted by @qwqcode in https://github.com/ArtalkJS/ArtalkGo/issues/14#issuecomment-1042642968_

**Comment by weijie-he** [comment]
postgresql 可以吗？有试过吗？

**Comment by keven1024** [comment]
说实话大佬没必要考虑太多QAQ，大多数站点评论没多少的，手动迁移也不是特别困难的事情。导出sql文件直接改字段，python脚本等都能解决问题。开源的东西没必要每个方面都做的十全十美，做好最基本的，剩下的交给社区。

推荐一篇关于适合开源维护者的文章: https://drewdevault.com/2021/06/14/Provided-as-is-without-warranty.html
![屏幕截图 2022-02-17 184644](https://user-images.githubusercontent.com/99848979/154463113-a7229a9e-8182-4a5a-97d1-9b0ecc880094.png)

**Comment by imycard** [comment]
> 说实话大佬没必要考虑太多QAQ，大多数站点评论没多少的，手动迁移也不是特别困难的事情。导出sql文件直接改字段，python脚本等都能解决问题。开源的东西没必要每个方面都做的十全十美，做好最基本的，剩下的交给社区。
> 
> 推荐一篇关于适合开源维护者的文章: https://drewdevault.com/2021/06/14/Provided-as-is-without-warranty.html ![屏幕截图 2022-02-17 184644](https://user-images.githubusercontent.com/99848979/154463113-a7229a9e-8182-4a5a-97d1-9b0ecc880094.png)

你要是能贡献代码或者提供建议就贡献，只是一个正常反馈bug、解决bug的过程被你上纲上线，还在我的issues里指责我发issues，并发收费解决连接，利用作者尚未解决的bug企图盈利。本来就是开源项目，发现bug难道不需要向作者反馈吗？反馈了一定就必须是作者解决？你有能力你也可以提交代码修补或改进啊。你为啥不希望改进的十全十美，因为完善后你这样的人无利可图了。

做人不能太无耻！！！
<img width="278" alt="微信截图_20220218130121" src="https://user-images.githubusercontent.com/3360809/154621525-02770cab-f41c-4a81-97dd-1811d029fc6a.png">
<img width="522" alt="微信截图_20220218130212" src="https://user-images.githubusercontent.com/3360809/154621529-caca3c01-65d1-41d7-8e39-4c078393d87f.png">

**Comment by qwqcode** [comment]
已修复
https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.0.6
