### ISSUE TITLE
关于连接 PostgreSQL 问题

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/ArtalkGo#16]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/22412567/155847128-99e00ed6-c519-49f7-b0e5-ded35ddfe484.png">

由于 model 定义了很多 boolean 类型的字段，使用 gorm 进行查询 where 方法查询很多地方直接传递了字符串 `xxx = 1`，在 MySQL 数据库和 SQLite 下 gorm 拼接的语句能正常工作。

参考：https://github.com/ArtalkJS/ArtalkGo/commit/f420fb5cfd420a5c0dd7eb99bc7b5898e7749050

然而，由于 pgsql 字段类型丰富，自带 boolean 字段类型；而 MySQL 本身无，故 gorm 创建字段类型 `tinyint` 来替代。导致了 pgsql 数据库和 MySQL 查询语句的差异性。

解决办法：将所有 boolean 字段类型改成 int，消除 gorm 创建 table 在不同数据库间的类型差异性。

另外还有很多问题，MySQL 和 SQLite 外键约束功能正常，而 PgSQL 测试不正常。

参考：https://github.com/go-gorm/gorm/issues/3624

适配难度较大，需要一定的时间和精力，暂时搁置。

目前仅测试兼容 MySQL 和 SQLite 两种数据库。

**Comment by weijie-he** [comment]
这个问题我看 waline 那边是为不同的数据源写了不同的建表语句。也许你可以参考一下
[walinejs](https://waline.js.org/guide/server/databases.html)

**Comment by qwqcode** [comment]
v2.1.3 已兼容 PostgreSQL
https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.3
