### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by fifsky** [ArtalkJS/ArtalkGo#17]
看了作者的作品，小小年纪能有如此造诣实属不易，加油
另给一点不成熟的小建议

1、尽量采用依赖注入的方式进行开发，比如`lib.DB`这种全局变量最好不用，虽然开发起来比较简单，但是不利于扩展，也不利于测试，推荐使用google wire，https://github.com/google/wire
2、模块之间尽可能的使用DDD思想进行拆分，基于接口开发，利于mock单元测试

一点小建议，希望对你有帮助

**Comment by qwqcode** [comment]
哈哈，谢谢你的鼓励！

在项目的开发过程中，一些功能因为之前代码组织得不好，并且没有加测试，逐渐变得难以维护，这是我需要学习和进步的地方。

我了解到 “设计模式”，并开了一个 [仓库](https://github.com/qwqcode/DesignPatterns) 记录笔记，正在持续学习当中。

非常高兴代码能够被浏览！谢谢你的帮助！ 😆
