### ISSUE TITLE
Artalk支持 远程Redis来缓存嘛

### ISSUE THREAD

**Issue by chuyua** [ArtalkJS/ArtalkGo#19]
我看兼容性下有句
高效缓存：支持 Redis, In-Memory
但是我没找到如何让Artalk远程连接Redis数据库

**Comment by qwqcode** [comment]
🤣 性能暂时还够用，连接 Key-Value 类型数据库缓存功能还没做哦

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/ArtalkGo/commit/72d205f3e9871f5871f9304a86233bdc499b33b4

下一个版本支持了

关联：https://github.com/ArtalkJS/ArtalkGo/issues/24

**Comment by qwqcode** [comment]
v2.1.3 已支持

https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.3
