### ISSUE TITLE
upgit 图片上传

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/ArtalkGo#22]
上传成功后能否也把图片文件删掉

https://github.com/ArtalkJS/ArtalkGo/blob/3b3947c1c18c31e2714b7ca7cf2619fcf376cfee/http/api_main_img_upload.go#L156-L171

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/ArtalkGo/commit/95e387f40ff3ea2c5e91cc2dea5cb39391bc5f6b

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/ArtalkGo/commit/1eff8309ea6b56b5fb0102a94bba8fc358c06dd2#diff-c5f542eb71c5aa239ef0f21ccc55d37cd81a394643895b42247394e7534f1741R120

v2.1.3
