### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/ArtalkGo#24]
![image](https://user-images.githubusercontent.com/22412567/164723731-68e5c8bb-84ba-4cf9-8acb-d00d98eaf46b.png)

目前性能太辣鸡了 😅

**Comment by xiamuguizhi** [comment]
可以的！

**Comment by qwqcode** [comment]
![image](https://user-images.githubusercontent.com/22412567/164763150-460e7fc1-ac13-4457-a199-dedadd451807.png)

https://github.com/ArtalkJS/ArtalkGo/commit/d1986c4f6f6dfa7b93051aace4911108fb884254

加上缓存后性能大幅提升

`/api/get` 层级嵌套模式下，100~50000 请求，服务器配置 6C-12T i5-10400 16GB，QPS 基本稳定一千左右

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.3
