### ISSUE TITLE
[Bug Report] 开启评论审核后无法发送回复通知

### ISSUE THREAD

**Issue by leirock** [ArtalkJS/ArtalkGo#30]
开启所有评论都需要审核后

```yaml
moderator:
  pending_default: true 
```

存在以下问题：

- 管理员审核通过后，回复该评论无法自动通过审核，也需要手动通过审核
- 回复该评论后，即使手动通过审核，也无法给原评论用户发送回复通知邮件（取消评论审核后，回复评论的通知可以正常发出）

希望是这样的逻辑：

- 管理员审核通过后，回复该评论应该自动通过审核，并同时发出回复通知邮件
- A 用户评论（管理员通过审核），B 用户给 A 用户该条评论回复，管理员对 B 用户的回复审核通过后，给 A 用户发出评论通知

**Comment by qwqcode** [comment]
### 关于第二个问题

确实存在这个问题，之后应修改为：当子评论审核通过后，向它的父评论发送邮件通知。

### 关于第一个问题

我认为如果管理员审核通过 Root 评论后，回复它的子评论「不应该」自动通过审核。
否则，如果小广告评论回复 Root 评论，那审核就失效了。

- Root 评论：第一等级的评论 (rid=0)
- 子评论：Root 评论下的子评论 (rid=父评论ID)

**Comment by leirock** [comment]
关于第一个问题，不知道我们的理解是不是有差异。

我的意思是，管理员回复的任何内容，都应该自动通过审核（不是只第三者回复通过的评论时可以自动通过审核）。现在的情况是，管理员回复评论也需要自己手动通过审核。

**Comment by qwqcode** [comment]
知道了，你的意思是管理员用户自己的评论应该自动通过审核，仅普通用户评论才是待审状态，这确实是一个 BUG。

相关代码：https://github.com/ArtalkJS/ArtalkGo/blob/master/http/comment_add.go#L127

**Comment by leirock** [comment]
是的，我就是这个意思～

**Comment by qwqcode** [comment]
😄 OK！

**Comment by leirock** [comment]
而且现在因为管理员的回复也是待审状态，所以回复普通用户的评论也是无法发出通知邮件的。

**Comment by qwqcode** [comment]
我考虑到了一种情况：审核通过后发送邮件通知，需要修改 [/http/admin_comment_edit.go#L86](https://github.com/ArtalkJS/ArtalkGo/blob/master/http/admin_comment_edit.go#L86) 的代码，需要注意判断邮件曾经是否已经发送过，否则当修改评论待审核状态的时候，会重复发送邮件。

**Comment by leirock** [comment]
是的，变更审核状态后，需要判断一下之前有没有通知过。因为可能存在之前通过审核，然后又进入待审状态，过段时间又批准这条评论的情况，这种情况下需要判断一下之前有没有发出过通知。

**Comment by qwqcode** [comment]
> 而且现在因为管理员的回复也是待审状态，即使这条回复手动通过审核，也是无法发出通知邮件的。所以正常来说应该是管理员回复自动过审核，并正常发出通知邮件。

确实，管理员用户应该拥有最高权限，无任何限制。之前设计程序没有考虑到这种情况，感谢反馈。

**Comment by qwqcode** [comment]
还想到了一种情况，如果是管理员修改评论审核状态，而这个评论又正好是回复管理员的，那就无需再发送邮件通知了。

**Comment by qwqcode** [comment]
这个通知功能实在是太复杂了 😅😅

**Comment by qwqcode** [comment]
虽然还没测试，但应该是修好了

https://github.com/ArtalkJS/ArtalkGo/commit/965946083684b2105bf627986fa116087829b19b

**Comment by qwqcode** [comment]
可以试试 v2.1.8 测试版：https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.8-alpha.1

**Comment by leirock** [comment]
已测试 `2.1.8-alpha.2`，

**解决了以下问题**

开启评论审核后，

- 管理员评论回复后直接通过审核，并给用户发送通知邮件
- B 用户给 A 用户回复，管理员通过审核后，给 A 用户发送通知邮件

**存在以下问题（也可能是 feature）**

不论是否开启评论审核，都存在

- B 用户给 A 用户回复，不会给管理员发出任何通知（邮件和多元通知均无）。

我理解的是，不论是否开启评论审核，任何普通用户发布评论应该都通知管理员，以便于及时对评论内容进行管理。当然如果认为这样都通知管理员没必要，是否提供一个配置的开关进行设置。

-------
其他通知情况未测试。

**Comment by qwqcode** [comment]
增加 `admim_notify.noise_mode` 选项，当设置为 `true` 时，B 用户给 A 用户回复，会向管理员发送通知。但默认为关闭状态。

https://github.com/ArtalkJS/ArtalkGo/commit/2af6e3e213a395b316e24c0bf05107f89bea216d

**Comment by leirock** [comment]
好耶！那这个issue应该可以关闭了～

**Comment by qwqcode** [comment]
v2.1.8 发布，已做过大量通知相关测试，应该没问题了
