### ISSUE TITLE
随机查询

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/ArtalkGo#34]
https://github.com/ArtalkJS/ArtalkGo/blob/ed547206e605412759d82485d5477b4865596924/http/stat.go#L136

mysql/mariadb 的随机函数是 `rand()` 吧。

**Comment by qwqcode** [comment]
😅😅😅

**Comment by inkss** [comment]
另外能不能加这么一个Api，根据网站名称，用户名，邮件查询当前用户是否存在未读通知，返回数量和通知内容。

拿来实现：访问网站时，欢迎用户并提醒用户查阅未读消息。

**Comment by qwqcode** [comment]
OK 😀

**Comment by qwqcode** [comment]
那个模糊查询以后再做了，我决定引入 Graphql，想怎么查怎么查

用户未读信息查询其实有现成的 API：

POST `/api/user-get`：

- name：用户名
- email：邮箱
- site_name：站点名

响应体：

```json
{
  "success": true,
  "data": {
    "is_login": false,
    "unread": [
        {
            "id": 419,
            "user_id": 76,
            "comment_id": 233,
            "is_read": false,
            "is_emailed": true,
            "read_link": "https://artalk.js.org/?atk_comment=233&atk_notify_key=xxxxxxx"
      }
    ],
    "unread_count": 3,
    "user": {
      "id": 233,
      "name": "用户名",
      "email": "邮箱@gmail.com",
      "link": "链接",
      "badge_name": "管理员",
      "badge_color": "#FF6C00",
      "is_admin": true,
      "site_names": null,
      "site_names_raw": "",
      "receive_email": true
    }
}
```

**Comment by inkss** [comment]
> 所有 API 查询得到的评论数据在后续版本中增加 `content_marked` 字段，为后端 Markdown 解析后的 content

👌 感谢

**Comment by qwqcode** [comment]
新版构建已发布 [v2.1.9](https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.9)
