### ISSUE TITLE
Windows系统下时区异常

### ISSUE THREAD

**Issue by Kengxxiao** [ArtalkJS/ArtalkGo#35]
## 问题
我在一台新装的Windows Server 2019上部署，无论将```timezone```设为何值结果均等效于```UTC+0```。
![image](https://user-images.githubusercontent.com/11478651/172067364-6a265dee-eecf-4b1c-a220-dd34859f5535.png)
在debug模式可以看到这里insert了一个19:28:58进去，但我是在第二天的3:28启动的。
实际上，在添加评论的时候，在前端显示的结果也会是**8小时前**。

## 可能的原因
由于我不太了解Golang，所以去查了一下原因，找到了语言下的一个issue
https://github.com/golang/go/issues/38453

https://github.com/ArtalkJS/ArtalkGo/blob/ed547206e605412759d82485d5477b4865596924/config/init.go#L67
应该是这里出的问题。

同时根据上面issue提供的线索，我用procmon探了一下zoneinfo.zip的读取，是在```运行盘符:\usr\local\go\lib\time\zoneinfo.zip```上。我拷了一份过去，目前工作正常，不过这个问题确实影响在win上的直接部署。

**Comment by qwqcode** [comment]
这确实是一个问题，感谢反馈。

这个问题仅发生在 Windows 操作系统，目前**临时**的解决办法是：

1. 下载一份时间数据库 zoneinfo.zip 到你的 Windows Server 服务器，例如：`D:/zoneinfo.zip`
    
    https://github.com/golang/go/blob/master/lib/time/zoneinfo.zip

2. 配置环境变量 `ZONEINFO` 如图：

<img width="863" alt="image" src="https://user-images.githubusercontent.com/22412567/172109597-4888cb6f-5b0d-4354-80f8-bd88ba74ce87.png">

3. 重新打开命令行运行即可

或者可以直接命令行执行 `set ZONEINFO=D:/zoneinfo.zip` 临时修改环境变量。

**Comment by qwqcode** [comment]
这是 Go 程序一个普遍存在的问题（如果用了 time.LoadLocation 函数），LoadLocation 这个函数依赖于 [IANA Time Zone Database](https://www.iana.org/time-zones) (简称 tzdata) 数据库，一般 Linux 系统都是自带的，而 Windows 系统没有。

所以如果没有这个数据库文件的话，就会去查 `$GOROOT/lib/time/zoneinfo.zip`，但需要装了 Golang 编译器才有。

可以手动配置 `ZONEINFO` 这个环境变量来指定时间数据库文件。

为了简单起见，之后我打算把这个文件内置到程序 exe 文件中，无需再额外配置。

**Comment by qwqcode** [comment]
看了一些相关内容，最后打算仅在编译 Windows 版的时候，给 Golang 编译器带上 `-tags timetzdata` 参数，内置到 exe 文件中，但 exe 文件会增大 800K

- https://github.com/golang/go/issues/38017
- https://go-review.googlesource.com/c/go/+/224588/
- https://github.com/golang/go/issues/21881

**Comment by qwqcode** [comment]
新版构建已发布 [v2.1.9](https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.9)
