### ISSUE TITLE
管理员打开侧栏正常，一般用户打开提示错误：非法请求：Referer 不被允许，无法获取评论列表数据 点击重新获取

### ISSUE THREAD

**Issue by Bakumon** [ArtalkJS/ArtalkGo#36]
感谢作者提供如此优秀的开源项目🙏🙏🙏

在使用中遇到了这个问题，不太懂相关代码，希望好心人能帮忙解答下🙏

具体错误如下：
<img width="336" alt="image" src="https://user-images.githubusercontent.com/12182189/172089147-2f5dcc90-509b-43d3-8249-e4c3a9f03764.png">

```
​ hello artalk-sidebar
index.f7f00175.js:1 hello artalk-sidebar
index.f7f00175.js:1 非法请求：Referer 不被允许
onError @ index.f7f00175.js:1
(anonymous) @ index.f7f00175.js:1
a @ index.f7f00175.js:1
index.f7f00175.js:1 Uncaught (in promise) Object
a @ index.f7f00175.js:1
```

**Comment by qwqcode** [comment]
解决方法是：将 `后端域名` 例如：`https://artalk.qwqaq.com` 也填入配置文件的 `trusted_domains` 项目中

**Comment by Bakumon** [comment]
感谢感谢，可以了

**Comment by qwqcode** [comment]
后端设计了通过 Referer 来限制访问，为了实现多站点共用同一套后端程序，而隔离彼此的操作。

例如限制：站点 A 无法在客户端将评论数据插入到 站点 B 中。

之后会修改一下，将服务器的 hostname 默认加进 trusted_domains 配置项中。

**Comment by qwqcode** [comment]
感谢反馈

**Comment by qwqcode** [comment]
新版构建已发布 [v2.1.9](https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.1.9)
