### ISSUE TITLE
配置可信域名后前端依旧提升跨域不能访问

### ISSUE THREAD

**Issue by fcwys** [ArtalkJS/ArtalkGo#38]
前端控制台信息：
![image](https://user-images.githubusercontent.com/28641034/172315030-60f07c94-05ee-4202-88be-3f4be5c14c55.png)

后端配置：
![image](https://user-images.githubusercontent.com/28641034/172315103-41280450-ae21-4121-8c60-50ad0fd59c98.png)

**Comment by qwqcode** [comment]
已修复，补充更新 v2.1.9/60ed699：[升级文档](https://artalk.js.org/guide/backend/update.html)

**Comment by qwqcode** [comment]
但是非常不建议将 `trusted_domains` 设置为 '*' 无限制，因为这会导致 CSRF 攻击隐患
