### ISSUE TITLE
api 返回最新评论，增加返回用户头像地址。。

### ISSUE THREAD

**Issue by jerryc127** [ArtalkJS/ArtalkGo#42]
希望 api 返回最新评论，增加返回用户头像地址。。

**Comment by qwqcode** [comment]
这个没有必要，返回的数据中有 email MD5 计算后的值，可以参考 gravatar API

**Comment by qwqcode** [comment]
😉 当然，如果以后做了用户注册的功能，可以加一个自定义头像

**Comment by jerryc127** [comment]
也是 
贪方便
那就不用还去判断用户是不是设置了 gravatar cdn 什么
