### ISSUE TITLE
管理员地址是什么，文档没介绍后端管理地址，没找到

### ISSUE THREAD

**Issue by terwer** [ArtalkJS/ArtalkGo#44]
管理员地址是什么，文档没介绍后端管理地址，没找到，不知道怎么访问后端，管理评论和配置

**Comment by aaro-n** [comment]
看这里，https://artalk.js.org/guide/frontend/sidebar.html
引入JS和CSS后，填写用户名和邮箱，可以弹出管理界面。

**Comment by terwer** [comment]
感谢，问题已经解决~
