### ISSUE TITLE
导入评论时必须指定目标站点 URL的问题

### ISSUE THREAD

**Issue by AlliotTech** [ArtalkJS/ArtalkGo#45]
哈喽 非常感谢作者开源  
在导入valine历史评论的过程中发现一个问题： 
导入评论时必须指定 目标站点 URL  如 https://xxx.com  
这样会让导入的那些评论的 page_key 字段自动拼接目标站点 URL  
而如果前端 实例化时`pageKey` 为相对路径时，就没法正确的展示评论，必须手动去数据库将历史评论的 目标站点 URL 前缀去除。

**Comment by AlliotTech** [comment]
同时，如果前端 pageKey 为相对路径时，邮件提醒里也会为相对路径

**Comment by qwqcode** [comment]
pageKey 为相对路径时，需在控制中心填写站点的 URL，参考：[邮件通知 | Artalk 文档](https://artalk.js.org/guide/backend/email.html#%E8%AF%84%E8%AE%BA%E5%9B%9E%E5%A4%8D)

“导入的那些评论的 page_key 字段自动拼接目标站点 URL”，这个可以在导入时填入启动参数：`{"t_url_resolver": false}` 关闭，下一个版本将会把这个参数默认为关闭状态，感谢反馈
