### ISSUE TITLE
使用控制中心自带的导入其他系统的评论功能成功后不能在评论表单下面显示，只能在控制中心看

### ISSUE THREAD

**Issue by drinktea1a** [ArtalkJS/ArtalkGo#46]
感谢作者为社区的贡献，不知道为什么会出现次问题，迁移时输入了站点名称和站点url（此处说明，评论系统使用的是二级域名，例如：博客站点是：www.x.com, 评论系统为：resp.x.com)， docker日志：
![image](https://user-images.githubusercontent.com/85236917/189511724-31f69786-7536-4e96-a1f0-237ae0ac5a73.png)

**Comment by qwqcode** [comment]
Duplicate of #45
